### ISSUE TITLE
Error when including ejs partial

### ISSUE THREAD

**Issue by cstapetrei** [mandarineorg/mandarinets#146] opened 2020-08-19 12:37 UTC
**[Details]**
I get the following error when trying to include an ejs partial.
I have the standard project structure recommended by the docs.

app.ts

```
import { MandarineCore } from "https://deno.land/x/mandarinets@v1.5.0/mod.ts";

import "./controllers/PublicController.ts";

new MandarineCore().MVC().run();
```
PublicController.ts

```
import { Controller, GET, Render, Model, ViewModel } from "https://deno.land/x/mandarinets@v1.5.0/mod.ts";

@Controller()
export class PublicController {
    @GET('/')
    @Render('index.ejs')
    public index(@Model() model: ViewModel) {
        model.setAttribute('page',{});
        model.setAttribute('menu',{});
        return model;
    }
}
```
index.ejs
```
<!DOCTYPE html>
<html>
<head>
    <%- include("/partials/meta", {page: page}); %>
    <title>title</title>
    <link rel="stylesheet" href="/css/all.min.css">
    <link rel="stylesheet" href="/css/bootstrap.min.css">
```
**[Stacktrace]**

```
[ERROR | Wed Aug 19 2020 15:20:08 GMT+0300 (GTB Daylight Time)] [4996] [MandarineMVC.class] Fatal error [
  [
    Error: ejs:4
    2| <html>
    3| <head>
>>  4|     <%- include("/partials/meta", {page: page}); %>
    5|     <title>title</title>
    6|     <link rel="stylesheet" href="/css/all.min.css">
    7|     <link rel="stylesheet" href="/css/bootstrap.min.css">

Node.js fs module is not supported by jspm core. Deno support here is tracking in https://github.com/jspm/jspm-core/issues/4, +1's are appreciated!
    at Object.unimplemented [as fileLoader] (https://dev.jspm.io/npm:@jspm/core@1.1.1/nodelibs/fs.js:1:32)
    at fileLoader (https://dev.jspm.io/npm:ejs@3.1.3/lib/ejs.dew.js:288:20)
    at handleCache (https://dev.jspm.io/npm:ejs@3.1.3/lib/ejs.dew.js:228:18)
    at includeFile (https://dev.jspm.io/npm:ejs@3.1.3/lib/ejs.dew.js:322:12)
    at include (https://dev.jspm.io/npm:ejs@3.1.3/lib/ejs.dew.js:688:18)
    at eval (eval at compile (https://dev.jspm.io/npm:ejs@3.1.3/lib/ejs.dew.js:656:14), <anonymous>:12:17)
    at anonymous (https://dev.jspm.io/npm:ejs@3.1.3/lib/ejs.dew.js:691:19)
    at Object.exports.render (https://dev.jspm.io/npm:ejs@3.1.3/lib/ejs.dew.js:417:39)
    at renderEjs (ejs.ts:10:14)
    at Function.render (renderEngine.ts:41:16)
  ]
]
```
**[OS]**
Windows 10 or Debian 10.3 with KDE

**[Environment]**
 - Mandarine version: 1.5
 - Deno version 1.3
 - Deno v8 version 8.6.334
 - Deno typescript version 3.9.7

**[Additional]**
I'm using denon to restart the server on changes with the following config
```
{
  "$schema": "https://deno.land/x/denon/schema.json",
  "allow": [ "net", "env", "run", "write", "read"],
  "watch": false,
  "tsconfig": "tsconfig.json",
  "scripts": {
    "dev": {
      "cmd": "deno run src/main/mandarine/app.ts",
      "desc": "Run dev",
      "watch": true,
      "inspect": "127.0.0.1:9229"
    }
  },
  "watcher": {
    "interval": 350,
    "exts": ["js", "jsx", "ts", "tsx", "json", "html", "ejs"],
    "match": ["*.*"],
    "skip": ["*/.git/*"],
    "legacy": false
  }
}
```

**Comment by andreespirela** [comment] 2020-08-19 12:43
Can you share your project structure? So your folders and all that @cstapetrei . I'd like to have that in order to get closer to reproduce it, thanks

**Comment by cstapetrei** [comment] 2020-08-19 12:45
Sure

![Annotation 2020-08-19 152629](https://user-images.githubusercontent.com/2313058/90636172-e7989480-e232-11ea-8531-c5f953f62839.jpg)

**Comment by andreespirela** [comment] 2020-08-19 13:13
> Sure
> 
> ![Annotation 2020-08-19 152629](https://user-images.githubusercontent.com/2313058/90636172-e7989480-e232-11ea-8531-c5f953f62839.jpg)

I see, so, as far as I understand the template inclusion must be done considering the current working directory of Deno. In that scenario, you would do <%- include("./src/main/resources/templates/partials/meta.**extension**", {page: page}); %>

So if your file is called `meta.html`, it would be: `include("./src/main/resources/templates/partials/meta.**html**"`. This is just a theory, I know someone had the same issue with Denjucks once, I think it's worth trying it. @cstapetrei

**Comment by andreespirela** [comment] 2020-08-19 13:19
> > Sure
> > ![Annotation 2020-08-19 152629](https://user-images.githubusercontent.com/2313058/90636172-e7989480-e232-11ea-8531-c5f953f62839.jpg)
> 
> I see, so, as far as I understand the template inclusion must be done considering the current working directory of Deno. In that scenario, you would do <%- include("./src/main/resources/templates/partials/meta.**extension**", {page: page}); %>
> 
> So if your file is called `meta.html`, it would be: `include("./src/main/resources/templates/partials/meta.**html**"`. This is just a theory, I know someone had the same issue with Denjucks once, I think it's worth trying it. @cstapetrei. Let me know the results & the code you have used when trying this

This accordingly to your current working directory, if you’re running your entry point one level deep, then it would be something like `../src/......`

**Comment by cstapetrei** [comment] 2020-08-19 14:02
Tried a few paths

```<%- include("./src/main/resources/templates/partials/meta.ejs", {page: page}); %>```  ==> Could not find the include file "./src/main/resources/templates/partials/meta.ejs"

```<%- include("/src/main/resources/templates/partials/meta.ejs", {page: page}); %>``` ==> Node.js fs module is not supported by jspm core.

```<%- include("/../resources/templates/partials/meta.ejs", {page: page}); %>```  (tried this since my entry point is in mandarine/app.ts) ==> Node.js fs module is not supported by jspm core.

Looks like a path issue...

**Comment by andreespirela** [comment] 2020-08-19 14:03
@cstapetrei I’ll follow up on this soon, I’ll try to make a small example and see if it fails

**Comment by andreespirela** [comment] 2020-08-19 14:35
@cstapetrei Unfortunately, JSPM where EJS is hosted does not support Deno, this is because EJS looks for the filesystem module of Node which is partly implemented in Deno. If you go to this file : https://dev.jspm.io/npm:@jspm/core@1.1.1/nodelibs/fs.js you will see the logic behind throwing that error. Not sure how we can approach to solve this in Mandarine as the engine is highly dependent on EJS for instance, if they don't support something then we can't override that behavior since it's an external effect, not a mandarine effect per se.

Let me know your thoughts to then proceed to close the ticket or make a decision.

**Comment by cstapetrei** [comment] 2020-08-19 14:40
Aha...i see

Oh well...at least we know it's not a mandarine issue. 👍 

I guess we're left for the moment with using EJS templates in deno without includes 😄 

You can close the issue since we have a clear answer.

Thanks.

**Comment by andreespirela** [comment] 2020-08-19 14:42
Closing this issue as it's an external issue from Mandarine. Will put a flag for investigation for future versions, the idea is to support all the features of EJS, if this is not possible in the long term I guess we will have to get rid of EJS or put it under flag.

**Closed by andreespirela** 2020-08-19 14:42 UTC
Labels: In discussion
